Repository apache/maven-archetype, pull requests merged in 2025-05, with the labels that each got.

#266 Remove clean from the PR template
  .github/pull_request_template.md
Labels: maintenance

#267 Lock down plugin versions in maven-archetype packaging
  archetype-common/src/main/java/org/apache/maven/archetype/creator/FilesetArchetypeCreator.java
  archetype-packaging/pom.xml
  archetype-packaging/src/main/resources/META-INF/plexus/components.xml
  archetype-packaging/src/site/apt/index.apt.vm
  maven-archetype-plugin/src/it/projects/ARCHETYPE-241_filter-directory/archetype/pom.xml
  maven-archetype-plugin/src/it/projects/ARCHETYPE-241_filter-directory/pom.xml
  maven-archetype-plugin/src/it/projects/ARCHETYPE-536_groovy-grape/archetype/pom.xml
  maven-archetype-plugin/src/it/projects/ARCHETYPE-536_groovy-grape/pom.xml
  maven-archetype-plugin/src/it/projects/ARCHETYPE-679_groovy-modules/archetype/pom.xml
  maven-archetype-plugin/src/it/projects/ARCHETYPE-679_groovy-modules/pom.xml
  maven-archetype-plugin/src/it/projects/build-and-run-its/pom.xml
  maven-archetype-plugin/src/it/projects/build-ignore-eol/pom.xml
  maven-archetype-plugin/src/it/projects/create-4/pom.xml
  maven-archetype-plugin/src/it/projects/create-5/pom.xml
Labels: enhancement

#268 Bump archetype descriptor version to 1.2.0
  archetype-models/archetype-descriptor/pom.xml
  archetype-models/archetype-descriptor/src/main/mdo/archetype-descriptor.mdo
Labels: enhancement

#264 Fix recognize project packaging by PomUtils
  archetype-common/src/main/java/org/apache/maven/archetype/common/util/PomUtils.java
  archetype-common/src/test/java/org/apache/maven/archetype/common/TestPomManager.java
  archetype-common/src/test/resources/projects/pom-manager/pom-sample-1.xml
  archetype-common/src/test/resources/projects/pom-manager/pom-sample-2.xml
Labels: bug

#270 [ARCHETYPE-674] Workaround for Maven 4
  .github/workflows/maven-verify.yml
  archetype-common/src/main/java/org/apache/maven/archetype/common/MavenJDOMWriter.java
Labels: bug
